### PR TITLE
Added C++ solution of 20. Valid Parentheses

### PR DESCRIPTION
**Pull request by MuditJain5**
#3 C++ solution of Leetcode 20. Valid Parentheses

### CODE REVIEW

**Comment by divyanshugit** [comment]
> #3 C++ solution of Leetcode 20. Valid Parentheses

Make sure you follow all the steps mentioned in [CONTRIBUTING.md](https://github.com/divyanshugit/Avid-Algorithms/blob/master/CONTRIBUTING.md)

**Comment by divyanshugit** [comment]
@MuditJain5 Can you please retry a make a PR. I think your first PR was not accepted due to my mistake.

**Comment by MuditJain5** [comment]
@divyanshugit I can't make a new PR because this PR is merged and my solution is also added in the leetcode folder.

**Comment by divyanshugit** [comment]
I mean if you want. You can solve one more question from LeetCode and submit a PR

**Comment by MuditJain5** [comment]
> I mean if you want. You can solve one more question from LeetCode and submit a PR

Ok. Thanks

**Pull request merged**
